### ISSUE TITLE
Javascript Errors

### ISSUE THREAD

**Issue by shackrock** [acidhax/chromecast-audio-stream#10]
Please see below.  This pops up randomly, usually back to back a few times, sometimes infinitely and I have to force quit the app.  Thanks!

![chromecast error](https://cloud.githubusercontent.com/assets/559901/12067215/2e873438-afc4-11e5-95a6-539174554695.png)

**Comment by Cubflyer** [comment]
You can deleting it by ending all tasks for both Electron and audio cast. Then, go to files and delete all the files for the program. You can then reinstall the program and try to troubleshoot if you wish

**Comment by Cubflyer** [comment]
End tasks in "Task Manager"
