### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by spieges** [acidhax/chromecast-audio-stream#11]
Help! Want this program to work really bad! Install goes fine and chromecasts display in system tray, but after selecting a chromecast to stream to- I hear the "ding" sound of the chromecast connected, but audio does not switch to chromecast, but continue to play from computer speakers! This is on a surface pro 4 running windows 10. Any help is greatly appreciated!

**Comment by Whitey05** [comment]
Same problem here. Hear the CC "ding" but no audio through chromecast, audio remains through PC speakers. Running on Win7.

**Comment by MrKuenning** [comment]
I am also seeing this with multiple windows 10 machines.   I would love to see this working.  Is there anything I can try different?

**Comment by wietseva** [comment]
I'm having the same problem on windows 10. This is the output I get when I run the test release.

```
Example app listening at http://192.168.1.4:3000
Spawned Ffmpeg with command: ffmpeg -list_devices true -f dshow -i dummy pipe:1
VIRTUAL DEVICE FOUND
data: { addresses: [ '192.168.1.7' ],
  query: [],
  type:
   [ { name: 'googlecast',
       protocol: 'tcp',
       subtypes: [],
       description: 'Google Chromecast' } ],
  txt:
   [ 'id=46f834bd99fe9161bacda5f68bc5eee6',
     've=04',
     'md=Chromecast Audio',
     'ic=/setup/icon.png',
     'fn=Hobo',
     'ca=4',
     'st=0',
     'bs=FA8FCA843E9A',
     'rs=' ],
  port: 8009,
  fullname: 'Hobo._googlecast._tcp.local',
  host: 'Hobo.local',
  interfaceIndex: 1,
  networkInterface: 'pseudo multicast' }
found device "undefined" at 192.168.1.7:8009
connected, launching app ...
app "[object Object]" launched, loading media [object Object] ...
Spawned Ffmpeg with command: ffmpeg -f dshow -i audio=virtual-audio-capturer -acodec libmp3lame -f mp3 pipe:1
An error occurred: ffmpeg exited with code 1: audio=virtual-audio-capturer: Input/output error

ffmpeg version N-69406-ga73c411 Copyright (c) 2000-2015 the FFmpeg developers
  built on Jan 29 2015 23:07:55 with gcc 4.9.2 (GCC)
  configuration: --arch=x86 --target-os=mingw32 --cross-prefix=/home/videostream/Downloads/sandbox/mingw-w64-i686/bin/i686-w64-mingw32- --pkg-config=pkg-config --enable-gpl --enable-libx264 --enable-avisynth --enable-libxvid --enable-libmp3lame --enable-version3 --enable-zlib --enable-librtmp --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libopenjpeg --enable-gnutls --enable-libgsm --enable-libfreetype --enable-libopus --disable-w32threads --enable-frei0r --enable-filter=frei0r --enable-libvo-aacenc --enable-bzlib --enable-libxavs --extra-cflags=-DPTW32_STATIC_LIB --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger --enable-libvpx --enable-libilbc --prefix=/home/videostream/Downloads/sandbox/mingw-w64-i686/i686-w64-mingw32 --enable-static --disable-shared --enable-libsoxr --enable-fontconfig --enable-libass --enable-libutvideo --enable-libbluray --enable-iconv --enable-libtwolame --extra-cflags=-DLIBTWOLAME_STATIC --enable-libzvbi --enable-libcaca --enable-libmodplug --extra-libs=-lstdc++ --extra-libs=-lpng --enable-libvidstab --enable-libx265 --enable-decklink --extra-libs=-loleaut32 --extra-cflags= --extra-cflags= --enable-nonfree --enable-libfdk-aac --disable-libfaac --disable-decoder=aac --enable-runtime-cpudetect
  libavutil      54. 18.100 / 54. 18.100
  libavcodec     56. 21.101 / 56. 21.101
  libavformat    56. 19.100 / 56. 19.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5.  9.101 /  5.  9.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[dshow @ 02843e00] Unable to BindToObject for virtual-audio-capturer
[dshow @ 02843e00] Could not find audio only device with name [virtual-audio-capturer] among source devices of type audio.
[dshow @ 02843e00] Searching for audio device within video devices for virtual-audio-capturer
[dshow @ 02843e00] Could not find audio only device with name [virtual-audio-capturer] among source devices of type video.
audio=virtual-audio-capturer: Input/output error
```

**Comment by Cnote43** [comment]
Same problem here. Windows 7 Lenovo laptop.

**Comment by ggvvlr** [comment]
same problem here

**Comment by luigiplr** [comment]
@acidhax :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation: :exclamation:

**Comment by matbeedotcom** [comment]
I'll look into this once I'm back from vacation, sorry about being quiet!

**Comment by ajvdplas** [comment]
Thanks Mathieu!

**Comment by ghost** [comment]
i have used the soft yesterday on my desktop PC without any issue, working very well.
Today, try it on 2 Dell laptop and like other people here, no sound.
Thanks for your help

**Comment by 5TDg9** [comment]
it tried it with two laptops running windows 8.1, no problems here. Maybe this is a windows 10 only problem?

**Comment by ghost** [comment]
My desktop PC is under Windows 10 (works fine)
For the 2 laptops one is under Windows 7 and the other one is under Windows 10 (both don't works)

**Comment by hardonthewind** [comment]
First off, I am using win10 on a Lenovo laptop. I can say that I am having the same problem with one caveat. The one caveat is that I am trying to use this with a chromecast audio device and not the regular chromecast device. This was due to my misreading an article on lifehacker.com and the "chromecast audio stream" name. I am getting a notification sound, though, when I connect or disconnect via the app so something is happening there. I am trying to use Mediamonkey with this so I can connect to my stereo system audio in via wireless. Hopefully, it won't take much to get this working with  the chromecast audio device as it recognizes it and appears to connect and disconnect to it. BTW, I think this is a great idea. Thanks.

**Comment by matbeedotcom** [comment]
I didn't realize it had a Lifehacker post! Sweet!

**Comment by hardonthewind** [comment]
http://lifehacker.com/how-to-send-your-computers-audio-to-a-chromecast-1750297581

**Comment by jiznon** [comment]
Not working here. Win7 Ultimate x64

I choose my Chromecast, my CC picks up a blank album with the text "Audio Caster" but the audio stays on my laptop.

**Comment by bpias** [comment]
Hi, just adding another voice to the choir - would be incredible to get this to work with Chromecast Audio (and Win 10). Many thanks for your hard work (PS also got here from the Lifehacker post, congrats on the growing impact of your creation).

**Comment by matbeedotcom** [comment]
I'm just dealing with an overflow of (real paid) work, before I can tackle any of these relatively easy to fix issues.

**Comment by hardonthewind** [comment]
No pressure here acidhax. I think most understand your situation. As long as there is hope. Take some time to chill. Thanks again.

**Comment by hardonthewind** [comment]
In order to contribute, I have been playing with this throughout the day. I have managed to run this through the command line and have the following logs. I was having trouble getting it to see the chromecast and showing the apparent "freeze" symptom that the #6 issue mentions. I think the symptom is just indicative of it not seeing the chromecast. When I finally did get it to allow me to select my chromecast, I was able to generate the second log. Hopefully this will be of some assistance.
[audiocast connect no sound log.txt](https://github.com/acidhax/chromecast-audio-stream/files/102616/audiocast.connect.no.sound.log.txt)
[audiocast freeze log.txt](https://github.com/acidhax/chromecast-audio-stream/files/102615/audiocast.freeze.log.txt)

**Comment by AltyFox** [comment]
It looks like paths with spaces are causing issues.   Try placing the files in a path with no spaces, like C:\ChromeAudio and see what happens

**Comment by hardonthewind** [comment]
Well, I know I had a hard time getting to the location via power shell because of the spaces so I guess that stands to reason. I created a folder in the root without spaces and copied the extracted files to that location. I finally managed get it to connect and now I am streaming flac files to the chromecast audio using Mediamonkey. I had some trouble getting the laptop sound muted so I wasn't hearing speakers playing the music along with the speakers that the chromecast is attached to. Not sure what I was doing wrong but when I muted the speaker volume in the system tray the chromecast would mute as well. Now it is not doing that so I can't say what the initial problem was with muting the laptop speakers. Thanks for the insight. Though, my main stereo system has an XP computer attached though there is an issue with this software working with this as I mentioned in #16, so not all my problems are solved. Thanks again.

**Comment by Cawoody** [comment]
Apologies, im not familiar with Github etc. but thought i would sign up to offer my solution as to how i got the program working on my 64 Windows 7 PC (thanks to Acidhax for the program btw, i was a bit disappointed by my purchase of a Chromecast audio and its reliance upon paid/subscriber apps prior to finding this).

I originally downloaded the current release, i would hear the "chimes" when connecting to my chomecast audio but then no actual audio output therein. I have rectified this as follows:

1) Install Node.js https://nodejs.org/en/download/
2) Download the current Audiocast1.0.0 release and extract the zip to a directory without spaces in the path (in my case C:\Audiocast)
3) Download the "Test" release of the program and extract this into your Audiocast  directory (i.e. C:\Audiocast) overwriting any existing files
4) Run Audiocast.exe 
5) System tray icon will appear, right click and select your Chromecast device, hear the "chimes" on the output device and begin streaming

This is how i got it working on my computer, its currently streaming to my hi-fi without issue as I type. I hope this works/helps others as the concept behind the program is great and one that im disappointed Google didn't offer out of the box with the Chromecast Audio

Cheers!

**Comment by dreverj** [comment]
For anybody still having issues, I am using Windows 10 on a Lenova Yoga 3 Pro. I was having the same issue where I could connect the app to my Google Chromecast device, but no audio was coming through. I tried extracting the app to a folder with no spaces, but this did not solve the issue.

To make the app work, i had to manually go into the resources\bin\driver folder and run the register_run_as_admin.bat script. Now after closing and re-running the audio-cast.exe app and connecting to Chromecast I can now hear my music from Windows Media Player. There is a 1-2 second delay on the audio, but works great, thanks @acidhax.

**Comment by krusse** [comment]
The instructions by dreverj fixed my issue. First time it's worked for me.

Thanks!

**Comment by dkbks** [comment]
Finally, after some weeks trying this and that, dreverj's instructions worked.  Thanks!  Currently listening to internet radio via RadioSure, a free program that I recommend - currently some 20,000+ stations listed and it sounds quite good (for compressed radio)

**Comment by jiznon** [comment]
Confirming that workaround from dreverj indeed works!

**Comment by ghost** [comment]
Confirming that workaround from dreverj works perfectly.
Thanks a lot

**Comment by ggvvlr** [comment]
tried the windows 10 workaround and still no luck :(

**Comment by ghost** [comment]
Works fine on both laptop and desktop in windows 10.
On the laptop i was obliged to uncompressed in a new folder without space in the name and not on system disk on which I have read-only issue like many other people in Windows 10.

**Comment by radabass** [comment]
For those still with problems to run it I was able to run it fine on windows 10 x64 after installing:

Visual C++ 2010 Redistributable x64 [https://www.microsoft.com/en-US/download/details.aspx?id=14632](url)
And:
Visual C++ 2010 Redistributable x86 [https://www.microsoft.com/en-US/download/details.aspx?id=5555](url)

I already have node installed so I don't know if it is important too.

Thank you.

**Comment by FightingSailor** [comment]
Running Windows 10.  I get the connecting ping to my Chromecast Audio device but then no other audio stream. Stays with PC speakers.

Tried @dreverj workaround.  Still no joy.  Have Visual C++ (both versions) installed.  Help please?

**Comment by FightingSailor** [comment]
Cracked it.  Thank you Cawoody and, especially, Acidhax. Unlocked the real benefit of these devices. :-)

**Comment by lenlynch** [comment]
@FightingSailor What did you do to get it working?

**Comment by Pealy** [comment]
Yeah. Do let us know

**Comment by FightingSailor** [comment]
@lenlynch @Pealy

Essentially I went back and worked through all of the advice above really carefully.

I installed "Node"  - don't know if that helped or not. Cawoody's post above gives the details.

Next, I deleted the version of the files that I had because I noticed that it was extracted to C:\Programme Files\AudioCast - There is a space in this file location string so, as but2002 advises above, I downloaded the zip file again and then extracted it to C:\AudioCast.  That seemed to do the trick.

I'm afraid that I'm really a bit of a techno-duffer so can't give any more detailed advice than that offered by the team above, but I hope that helps.  Good luck.

**Comment by Pealy** [comment]
Cheers for that

**Comment by jimgardner** [comment]
Desperately trying to stream audio from my Windows 10 laptop (from itunes for example) to Google Chromecast audio device plugged in to my Soundbar.  I know the connection works as I am able to cast a Chrome web page (eg playing Internet Radio stations) and the sound is played on my soundbar BUT I really want to be able to stream ANY audio output from my laptop so I am not restricted to cast enabled apps.  When I run audio-cast.exe however nothing happens.  There is no cast icon showing in the Tray for me to launch.  I can see processes (Electron?) running in Task Manager though!

**Comment by AltyFox** [comment]
@jimgardner Are there any spaces in your path to the exe?

**Comment by jimgardner** [comment]
@but2002 No I created a new folder C:\CAS and put all the downloaded files, including the exe, into this folder.  I have tried running the exe from Windows and also tried running it from the command line,  Neither works.

**Comment by AltyFox** [comment]
@jimgardner  Can we see the logfile?

**Comment by jimgardner** [comment]
@but2002 
![capture](https://cloud.githubusercontent.com/assets/19714508/15773966/c2fbc076-2971-11e6-81d0-838db147f3b9.JPG)

This is a screenshot of what I see after running the program.  Is that what you mean or is there an actual log file somewhere on my hard drive?

**Comment by dmcritchie** [comment]
As others have suggested, changing the path to the executable so no folder had any embedded spaces did the trick for me.

I did not need to run register_run_as_admin.bat, presumably because my account has admin privileges.

Dennis

**Comment by drjp69** [comment]
Possible fix for some of you here: https://github.com/acidhax/chromecast-audio-stream/issues/52
