### ISSUE TITLE
Streaming in higher resolution with 24bit and 96kHz

### ISSUE THREAD

**Issue by 5TDg9** [acidhax/chromecast-audio-stream#12]
At the moment this tool is just able to play files with PCM with maxium of 48 kHZ, at least that's what my amp says one the display. Would it be possible to stream in higher resolution for more audiophil needs?

**Comment by lars18th** [comment]
Hi,

I like also to know if 44.1KHz (or even less) is supported.

Please, can you add a description in the Home about the formats (resolution) accepted?

**Comment by matbeedotcom** [comment]
It's definitely possible, I just need to make it configurable.

**Comment by moledig** [comment]
Like a lot of people out there I too am looking for a way to stream lossless audio to CC and CCA. I've tries Plex and BubbleUPnP but no matter what I do the audio gets transcoded into MP3. I love this idea of just casting the computer audio. Very clean solution but from what I have read about CCA your only choices are MP3 or WAV. So is there any way to tell FFmpeg to output a WAV? (Can I edit a config file?) That would be a good start. Then once that is working being able to cast some of my high resolution audio would be nice but right now I'm sick of the sound of MP3s even for background music. (sigh)
