### ISSUE TITLE
Printing Service downloaded instead of Chromecast Audio Stream

### ISSUE THREAD

**Issue by FA-Bubba** [acidhax/chromecast-audio-stream#121]
I tried to download the Chromecasy-Audio-Stream App, but only get a Bonjour Print Services App.  Where is the AudioCast App?

**Comment by Flonja** [comment]
Duplicate of #120

**Comment by FA-Bubba** [comment]
I found newer version here:

https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer
