### ISSUE TITLE
ffmpeg exiting

### ISSUE THREAD

**Issue by RJUPI** [acidhax/chromecast-audio-stream#15]
Edit: NVM - Icon is there but black instead of white. 

When I change the volume in the Pandora One application it takes about two seconds to take effect.

**Comment by matbeedotcom** [comment]
There is a delay, and I'll definitely be looking into how to reduce the delay.

**Comment by RJUPI** [comment]
Thanks for your quick response.

It would also be great if the volume was controlled by the volume control in the tray or with the multimedia volume keys on the keyboard.

**Comment by matbeedotcom** [comment]
It's odd, because for myself, it IS controlled by the keyboard + tray!

**Comment by RJUPI** [comment]
I am using a Behringer USB soundcard. 
I switched to the internal card and the volume does work now.

**Comment by RJUPI** [comment]
Another issue I have is that the volume level out of the PC is much much lower than the volume out of my IPhone or Android tablet when they are connected to the 2 Chromecasts. All volume levels are maxed out in the PC's mixer. The volume is the same whether I use Pandora or Windows Media Player.

![volume](https://cloud.githubusercontent.com/assets/16722600/12360851/f70bc254-bb7f-11e5-9a87-748a524a19e7.JPG)

**Comment by RJUPI** [comment]
I get a crash if I unplug 1 of 2 Chromecasts that I am streaming to and then plug it back it, then try to reconnect to it.

![crash](https://cloud.githubusercontent.com/assets/16722600/12361012/221b3712-bb81-11e5-98fe-e59ea7dcc40d.JPG)

**Comment by matbeedotcom** [comment]
Thanks for the reports!

**Comment by RJUPI** [comment]
Last report:

When I started downloading a file from another PC on the network, I suddenly experienced major latency between the two Chromecast Audio units. The only cure was to restart audio-cast.
