### ISSUE TITLE
Windows version clarification

### ISSUE THREAD

**Issue by hardonthewind** [acidhax/chromecast-audio-stream#16]
With the "audio-cast-1.0.0-win32-ia32" name for the file, I came to the conclusion from the win32 portion that this would work on Windows XP. When I tried to run it I received a dialog box stating that the file was not a windows application. So, perhaps a listing of which windows operating systems this will work on would be helpful. From what I have read here in the issue section it appears that probably one would need at least Windows 7 to use this. Thanks again.

**Comment by matbeedotcom** [comment]
It should work on Windows XP, but I absolutely have not tested it..

**Comment by hardonthewind** [comment]
I have a few more XP computers so I will try them and see what happens. I tried a couple of things on the one I was using but I was still getting a " not a valid windows application" dialog box.

**Comment by hardonthewind** [comment]
Well I am still getting the same message. However, when I tried to set up the xp computer for the chromecast audio with google's installer I received and error message and have subsequently discovered that it needs a minimum of Win7 to run. I do not know if your app was meant to work without the chromecast setup from google or not. If so, then it is a definite no go for xp.

**Comment by matbeedotcom** [comment]
It was probably just compiled for 64bit instead of 32bit, to be honest. Are you running 32bit windows?

**Comment by hardonthewind** [comment]
Yes, I am running XP 32bit. When I had these issues I tried it on my Win10 computer, which then ran save for the issues I noted in issue 11. Is this intended to work without the chromecast app?

**Comment by matbeedotcom** [comment]
Yeah, it works without any chromecast applications. It's 100% stand alone.

**Comment by Dale-614** [comment]
Is there a 32-bit version? I tried 0.2.5 but get "not a windows application". I am running WinXP!? (still)

**Comment by hardonthewind** [comment]
This is never going to work with XP. As I looked into it some more I discovered that XP does not have the ability to capture the audio stream. So a 32bit version is moot. I don't remember the exact technical issue with it but I gave up on getting this running on XP when I came across the information. Probably should have posted what I found out here then. Sorry, my bad for not doing so.

**Comment by mcprat** [comment]
I'm pretty sure that your XP system's ability to capture audio output is completely dependent on the sound card/driver. What's yours? Realtek?

See if you can find anything here: Start > (Settings) > Control Panel > Sounds, Speech and Audio Devices > Sounds and Audio devices > Audio tab
from: https://answers.microsoft.com/en-us/windows/forum/windows_xp-hardware/is-there-any-way-to-enable-stereo-mix-in-windows/e56077bf-e2ca-49e2-adc2-abaea9617aa3
