### ISSUE TITLE
Lag/Delay problem

### ISSUE THREAD

**Issue by fractalf** [acidhax/chromecast-audio-stream#21]
I'm experiencing 1-2 sec lag/delay using this. The chrome extension has a small lag also, but tiny compared to this. Anyone else?

**Comment by matbeedotcom** [comment]
Yes this is happening

**Comment by LillyWho** [comment]
My output is lagging behind by about 10 seconds using the application. I can play something and have the receiving device make an echo. I'm using the Nexus Player, in case that's relevant.

**Comment by tomganleylee** [comment]
I also am having this issue, the app works great and am loving it but i am having about a 5 second delay. Any ideas about why this is happing?
I am casting to a LG H7

**Comment by matbeedotcom** [comment]
Currently looking into it, but its not looking good. I'll investigate another method of capturing system audio, but it takes a little more system configuration.

**Comment by Geo1970** [comment]
Hi. Thank you for the program, it is great for listening to audio stored on the PC. 
I'm having the same problem syncing to video, a three or four second delay. Acidhax will you be able to let users know if and when you fix it?
