### ISSUE TITLE
Not Working At All and JavaScript Error 

### ISSUE THREAD

**Issue by AgentTrustNo1** [acidhax/chromecast-audio-stream#22]
![capture](https://cloud.githubusercontent.com/assets/17347320/13192810/fb0d9038-d73d-11e5-9309-d29a2cd71a1f.PNG)

I have been able to get the software to work at all. I keep getting this error when selecting the device. Also, can see what device I selecting, the pop-up window is in the top left corner of the screen, with the third right side showing only. 
![untitled](https://cloud.githubusercontent.com/assets/17347320/13192883/b945ed3e-d73e-11e5-8fbb-21d4d1f64b2a.png)

Please Help!

**Comment by brunur** [comment]
I'm just trying this app for the first time today and I have the exact same error message and the device name is missing yet the check mark is there, similar to the picture above. has anyone figured out a fix?

thanks.

**Comment by Ouston** [comment]
Same for me. :(

**Comment by matbeedotcom** [comment]
Please verify this is still an issue by testing https://github.com/acidhax/chromecast-audio-stream/releases/download/0.3/audio-cast-win32-ia32.zip
