### ISSUE TITLE
Can't disable and re-enable streaming

### ISSUE THREAD

**Issue by brxxbrxx** [acidhax/chromecast-audio-stream#23]
Hi, it's very nice app, but I have a problem on my laptop running on win10 64bit.
After laptop start, I can start the app, with right-clicking I choose my Chromecast. But when I try to disable streaming by unchecking Chromecast with right click, the stream continues. Chromecast plays its notification sound (when I enable it), but that is all. The only thing I can do is to select Close in right-click menu. But after doing that, when I start the Audio cast app again, nothing happens when I perform right-click on its icon and there is no way to start streaming again. I can only restart my laptop.

Has someone the similar issue?

**Comment by MobyUK** [comment]
Same with me on Windows 10 laptop.

Edit: Now even re-starting the laptop doesn't work. The tray icon is just completely unresponsive.

**Comment by MobyUK** [comment]
Does anybody reply to these comments?
I know it's a free piece of software, but if it worked, I wouldn't mind paying for it.
Some feedback would be appreciated anyway.

**Comment by hardonthewind** [comment]
I was having troubles getting this to run on a Win10 laptop but I managed to get it working after I posted command line generated logs in issue #11. The main problem were the spaces, as pointed out by @but2002, in the path to the executable. Check to see if you have a similar situation. You may just want to extract the files to a folder in the root of you hard drive to shorten the length of the path, making sure there is no spaces in the folder name. Worth a try and quick to do.

**Comment by MobyUK** [comment]
Unfortunately it hasn't worked for me. Still a dead tray icon.

**Comment by matbeedotcom** [comment]
@MobyUK I do reply but I'm trying to get work done and get these things released :P

**Comment by MobyUK** [comment]
I'm sorry for the comment. I do realise you have stuff to do.
Please accept my apologies.

**Comment by matbeedotcom** [comment]
All is forgiven, good child.

:P

**Comment by brxxbrxx** [comment]
I can confirm that the @but2002 hasn't worked for me, too. I have the executable in root. Without that, I hadn't been even able to run it.

@acidhax: thanks for response.

Edit: "one more thing": even though the streaming method works, its icon is still the same, without fill.
