### ISSUE TITLE
No Tray icon - not usable on Win10/64 bit....

### ISSUE THREAD

**Issue by smartinick** [acidhax/chromecast-audio-stream#24]
Sorry.... it works. it's simply not visible - black icon on black taskbar.... therefore it's the blind, leading the blonds.... forget this issue.... yes... maybe make icons that are visible - would help a bit :D

**Comment by pjdebruin64** [comment]
Here it's the other way around. There is a visible black icon on my (blue) taskbar, but it doesn't respond to right or left clicking.

**Comment by TeutonJon78** [comment]
Already reported under issue #13 . There's been no changes since then. If you go into the folder, you can find and manually edit the graphics. I just took them into a graphics program and used the brightness/contrast to keep increasing it until the pixels became white.

**Comment by nickrsan** [comment]
Lots of applications get around these kinds of issues with halos (black graphics with a subtle white border, etc). Maybe a pull request tweaking it slightly is in order if someone has a good version usable across a range of colors?

**Comment by matbeedotcom** [comment]
Fixing now
