### ISSUE TITLE
java script error

### ISSUE THREAD

**Issue by srouw** [acidhax/chromecast-audio-stream#26]
Program stays open and says it is still connected to chromecast but signal is lost.  Have close and reopen program and select chromecast again.  Thanks!!!
[java script error.pdf](https://github.com/acidhax/chromecast-audio-stream/files/157795/java.script.error.pdf)

**Comment by PrabhuArchi** [comment]
Please help me with this java script error for chromecast audio casting. Screenshot is attached for your reference. Please help.
![error](https://cloud.githubusercontent.com/assets/19375707/15275642/d6b0a3d4-1aee-11e6-9cac-2996b0227765.jpg)
