### ISSUE TITLE
ffmpeg not loading in volume mixer

### ISSUE THREAD

**Issue by srouw** [acidhax/chromecast-audio-stream#27]
Help!  I recently did a fresh install of Win7 64 and now audio-cast stopped working.  I love this program and can't live without it!  The program seems to start up properly.  I right click on the system tray icon and I can select my chromecast audio device but have not been able to get any sound out of it.  I did notice that the ffmpeg.exe no longer shows up in the volume mixer.  I'm assuming that's the problem?  The chromecast windows app finds my device and I get the startup sound out (I can stream music from chrome as well) but nothing streams from my pc.

I'd appreciate any help!  Thanks.

**Comment by norsemangrey** [comment]
Same problem here. Anyone found an answer?

**Comment by drjp69** [comment]
See here: https://github.com/acidhax/chromecast-audio-stream/issues/52
