### ISSUE TITLE
Group Cast support?

### ISSUE THREAD

**Issue by VadimRy** [acidhax/chromecast-audio-stream#28]
Thank you very much for developing this tool. Been using it daily.
Finally received and configured second ChromeCast Audio unit, however, Group Cast feature does not seem to working.
Any chance to implement it? 
Thank you in advance!

**Comment by VesNL** [comment]
Same here. Discovered this due to wanting to use foobar on my PC.

I did notice you can select multiple Chromecasts, don't know if that was the intended behaviour to replicate the group feature.

**Comment by Pealy** [comment]
I'd really like to see this too - would really open up the possibilities

**Comment by conzicast** [comment]
I'm interested too
I don't need to create a group... just select/choice the group

**Comment by petpap** [comment]
Any news on this?
Does MultiRoom work synched with Group Cast?
If not, does it work unsynched by casting to multiple Chromecasts individually?

It would be wonderful if you could use Foobar or other media players with Chromecast Audio to multiple chromecasts :-)
