### ISSUE TITLE
Share sourcecode please?

### ISSUE THREAD

**Issue by stereokai** [acidhax/chromecast-audio-stream#3]

**Comment by matbeedotcom** [comment]
The entire source code is available.

Index.js

**Comment by stereokai** [comment]
@acidhax What about app.exe and audio_sniffer?

**Comment by matbeedotcom** [comment]
app.exe just executes "node index.js"

and audio_sniffer is from https://github.com/rdp/virtual-audio-capture-grabber-device

**Comment by stereokai** [comment]
So why not simply add app.exe's source? :)

**Comment by matbeedotcom** [comment]
I don't have it, I used some application to make it... "Advanced BAT to EXE converter"
