### ISSUE TITLE
Any way to stop it timing out?

### ISSUE THREAD

**Issue by Pealy** [acidhax/chromecast-audio-stream#33]
I'd like to have this always stream from a pc but after a period of inactivity it stops. Works fine if I go back and re-select the Chromecast device but don't want to have to do that, Thanks.

**Comment by matbeedotcom** [comment]
Please verify this is still an issue by testing https://github.com/acidhax/chromecast-audio-stream/releases/download/0.3/audio-cast-win32-ia32.zip
