### ISSUE TITLE
Command line option?

### ISSUE THREAD

**Issue by Pealy** [acidhax/chromecast-audio-stream#34]
Would be great to be able to launch with one or more Chromecast (or group) in the command line to automatically start streaming..

**Comment by wikijm** [comment]
+1 for me. It will be very usefull for my Dad who is not able to use it with his screen reader software (See issue #30 )

**Comment by Pealy** [comment]
$15 to anyone who can make this happen! Just want to be able to launch with a single parameter - the name of the device, eg. "audio-cast MYCASTDEVICE".

Or even just the number of the device in the list "audio-cast 1" then "audio-cast 2" to start two instances, one sending audio to the first device in the list, the other to the second, you get the idea! Drop me a line if you think you can do it..

**Comment by conzicast** [comment]
250€ $ to anyone who can make this happen.... (launch multiple (ex.  list in txt file) chromecast audio)

**Comment by Pealy** [comment]
I'll up mine to $25 too -  come on people!

**Comment by Pealy** [comment]
**@conzicast** - how much do you need the ability to read from a text file? I'm paying someone to implement a command line option so that I can specify the name of the device. I could ask about reading a list from a text file if you want to chip in.

**Comment by conzicast** [comment]
i need to specify all my chromecast audio via command line, not only one.  (or specifiy a group)
the way for that does not matter to me.

by now I have resolved with linux and pulseaudio-dlna
https://github.com/masmu/pulseaudio-dlna
and with vlc I can choose the single cromecast audio or a chromecast audio GROUP.

but i'm interested to audio-cast yet, so.. you can go ahead

**Comment by Pealy** [comment]
Okay. I've asked the developer to see if a list of devices in the command line would be easy enough. 

I intend to launch multiple instances to cast to multiple devices.

**Comment by darkzbaron** [comment]
@Pealy Did you end up doing this? Where can I download your version?

**Comment by Pealy** [comment]
**@darkzbaron** I gave up in the end, the developer couldn't get it stable. I use a product call Airfoil now, it runs on the PC and sends audio to Airplay and Chromecast devices - and I can control with an Android app. It's not perfect either but it does me okay.

**Comment by darkzbaron** [comment]
@Pealy Ok understand but If I am not mistaken AirFlow can only play songs, not cast the sound from the System?

**Comment by Pealy** [comment]
**@darkzbaron** Airfoil from Rogue Amoeba isn't a player, it's a windows or iOs app which routes audio (from specific apps or just system audio) to Airplay or Chromecast. See https://rogueamoeba.com/airfoil/
It's free to try but you would need to pay for a licence. I've had good support from them btw.

**Comment by darkzbaron** [comment]
@Pealy. Ok noted, will check it out, thanks for the information

**Comment by MikeGahrns** [comment]
Thanks for the pointer to AirFoil.  While not perfect, it so far has been much more reliable in terms of casting than any other solution I have tried.   AirParrot also looked promising, but wouldn't cast to my Vizio speakers.  To a Vizio TV, it worked fine.

**Comment by Pealy** [comment]
Glad you like it - I also find it's not perfect but I can just about liv with it - biggest problem for me is running in a headless set-up, it really doesn't like being left running for a few days so I ended up adding a kill-and-restart function to my media player to save me tearing my hair out.
