### ISSUE TITLE
Windows 10 64 bit, connects to chromecast but no sound is transfered

### ISSUE THREAD

**Issue by PortableGoogle** [acidhax/chromecast-audio-stream#38]
I'm not sure if i'm suppose to do anything else besides select the streaming device, but no sound comes out the chromecast using this program.

**Comment by bmmcdaniel** [comment]
I'm having the same problem. Windows 10 64 bit. The program is running and I can select my chromecast audio device. I know its connecting because I get the beep sound from the device, but regular windows sounds aren't sent to the device. Any help?

**Comment by Pealy** [comment]
Might be worth looking at this discussion : #11 

I found that moving the program to a folder without a space ("C:\Chromecast") worked for me.

**Comment by bmmcdaniel** [comment]
Finally got it to work. I did all the following:
- Install node
- Install C++ 2010 packages
- placed in folder with no space ("C:\CAC")
- run register_run_as_admin.bat
- tried replacing ffmpeg and using ffprobe using freshly downloaded 32 bit and 64 bit versions.

Not sure what worked, but it works now.

Thanks so much. I love my new toys.

**Comment by do7slash** [comment]
Thanks bmmcdaniel, what worked for me as follows.

I'd already done:
- Install node
- Install C++ 2010 packages (both x86 and x64)
- placed in folder with no space: C:\CAS

The magic for me was:
- run as admin: register_run_as_admin.bat
- replaced ffmpeg and ffprobe using freshly downloaded 32 bit versions

**Comment by do7slash** [comment]
Sorry to add, if i then close CAS and re-open it, it still freezes in the taskbar and i have to reboot computer for it to work again.

**Comment by Pealy** [comment]
..same here. Tried every step, no audio from the device. I get the confirmation beeps to say it's been selected but no sound. I get the same ffmpeg error 1 problem as everyone else.  Casting audio from chrome to the device is just fine.

Such a shame, this has so much potential

**Comment by Pealy** [comment]
For info - the  "ffmpeg error 1" report is not necessarily a problem. I've had it working just fine even when this is shown when it's launched.

On the other hand, it sometimes works, sometimes doesn't. A very, very temperamental bit of code this. I've spent so much time trying to make it work but have had to admit defeat and give up.

**Comment by matbeedotcom** [comment]
Ugh, I'll work on it. Time is fleeting.

**Comment by drjp69** [comment]
Take a look here for a registry hack that fixed it for me:

https://github.com/acidhax/chromecast-audio-stream/issues/52

**Comment by bluesodium** [comment]
drjp69,  doesn't work for me :-(

**Comment by matbeedotcom** [comment]
Please verify this is still an issue by testing https://github.com/acidhax/chromecast-audio-stream/releases/download/0.3/audio-cast-win32-ia32.zip
