### ISSUE TITLE
Disable audio software when play on Chromecast Audio

### ISSUE THREAD

**Issue by NessunoIM** [acidhax/chromecast-audio-stream#40]
If I play a song with Windows Media Player or other software, the audio was duplicated, I can hear two sounds, one for my stereo system (connected at the Chromecast Audio) and one for laptop speaker. I solved silencing my periferic audio, but it is (obiviously) uncomfortable...

Chromecast Audio Stream installed on Windows 10 64-bit

**Comment by EricTousignant** [comment]
Hello, just wanted to add my name to this issue.

Especially with the delay (see issue #37), there is no reason for the app to leave the computer's sound on at the same time as the connected Chromecast. Maybe this could be an option (like in the AirPlay menu where you can select multiple speakers and activate/deactivate the sound from your PC).

**Comment by mcprat** [comment]
This application is not designed to have any control over your system's audio. It does only one thing which is grabbing a copy of the audio output and pushing it to the chromecast. The extensions and apps from Google work on the program level, so it is very easy to stop audio output to the system when audio is sent to the chromecast, but this application is system-wide, and enabling it to have control over your system audio might even cause other problems like audio driver crashing.
