### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by DVLP** [acidhax/chromecast-audio-stream#44]
I tried on 2 laptops with Windows 10. One is Pro and the other Home. Both are 64bits. After clicking on audio-cast.exe an icon appears in the tray but nothing happens  after clicking on it either left or right.

**Comment by bronco65** [comment]
I have the same issue with Windows 10 Home 64bit. The icon appears and I choose one of my Chromecast devices. On my iPhone's Google Cast app I can actually see the chosen Chromecast become active - Default Media Receiver. But no audio is going to the Chromecast, audio only plays to Windows PC connected speakers.

**Comment by dipteshkanojia** [comment]
I am facing the same problem on Windows 10 64 bit. Any help ?

**Comment by Danielo290881** [comment]
Here too, Same Problem. And i dont hear Music of my Speakers, but on pc

**Comment by Gionames** [comment]
I've tried on both 32 and 64 bit Windows 10 systems. In both cases:
1) Most often, when I (right) click on the tray icon, nothing happens
2) When the pop up window to connect to Chromecast manages to appear, it does so in the top left corner instead of bottom right corner. Also, most of times, in the pop up connection window, an empty space is shown in place of the Chromecast name 
3) In those cases where the Chromecast name appears in the connection window, clicking on that name results in Chromecast attempting to connect, but it constantly fails too. 

Edit: managed to get some success installing Bonjour as instructed in #31

**Comment by urteper** [comment]
Same problem here. Have tried on both a lenovo x220 with win10 and a lenovo t450s with win10, and pretty much tried most combinations of all the proposed solutions, but still cannot get it to work.

**Comment by Pealy** [comment]
> Have tried on both a lenovo x220 with win10 

Strange that - I have it working just fine on an X220 running W10

**Comment by urteper** [comment]
> Strange that - I have it working just fine on an X220 running W10

Yeah thats what does not make sense in my world. I really wonder what i have done (or not done), since i cannot make it work. 

I had it working on my x220 before i upgraded to win10 though...and it was working more or less perfectly (with the same lag most people experience, but working nonetheless).

**Comment by Pealy** [comment]
I take it back - it was working fine, now it only works sometimes. And sometimes shows all devices, sometimes misses one. On another PC, set-up in exactly the same way it doesn't work at all. Regrettably, I've now given up.

**Comment by sajattack** [comment]
god damnit matbee what did you do

**Comment by sajattack** [comment]
Master seems to work better. Update the releases @acidhax?

**Comment by luigiplr** [comment]
@acidhax is 200% ded.

All your issues belong to me.

**Comment by Pealy** [comment]
Are you picking up the baton? Would love to see this working reliably, loads of possibilities.

**Comment by matbeedotcom** [comment]
bloop bleep bloop

**Comment by matbeedotcom** [comment]
I'm just busy as tits

**Comment by connected-mgosbee** [comment]
I'm currently working on some issues, and will be releasing an update soon.

**Comment by matbeedotcom** [comment]
Please verify this is still an issue by testing https://github.com/acidhax/chromecast-audio-stream/releases/download/0.3/audio-cast-win32-ia32.zip

**Comment by DVLP** [comment]
@acidhax Thanks for the fix! Only tested at work with nothing to cast on but at least the menu appears. Have to try at home

**Comment by codlike** [comment]
@acidhax Overjoyed, fantastic, marvellous. Its never worked for me, and tried most of the tweaks on here, and been following since you released. Its working on Win 10 64 and 32. Almost lifechanging. Do you have a somewhere I could send you a donation for your hardwork?

**Comment by bluesodium** [comment]
doesn't work on win 10 64 bit.

get the bong but nothing transferred.

audio_sniffer issue??

if i try and run the bat file command it says the module cannot load. dependency issue?

**Comment by Pealy** [comment]
Here we go again.. I'd love to think this new release was going to work, fingers crossed!

**Comment by bluesodium** [comment]
fixed it..

in the driver directory and open register_run_as_admin.bat

change 
regsvr32  %~dp0/audio_sniffer.dll

to

regsvr32  %~dp0audio_sniffer.dll

run as administrator and ta da. Audio sniffer dll succeeded.

works a treat now.

**Comment by drjp69** [comment]
It still works for me, having previously manually edited the audio_sniffer.dll entry in the registry.

**Comment by Andulien** [comment]
Please have a look at my issue #56
It seems to have worked for some, if you copy the Programms folder to your Desktop and then run if from there.
