### ISSUE TITLE
Casting does not stop when deselecting Chromecast device

### ISSUE THREAD

**Issue by dmcritchie** [acidhax/chromecast-audio-stream#45]
I am running in Windows 10, and am able to cast to one or more devices, as intended. But when I deselect a device in the tray menu, the sound stops for a few seconds and then starts up again, even though the device is shown as deselected in the tray menu. While this is happening, the Chromecast app on my phone confirms that the device stops casting briefly and then starts casting again.

This consistently happens. Anyone else having this problem?

Thanks,
Dennis

**Comment by Pealy** [comment]
Same. Have spent way too much time & effort trying to get this app working reliably. I've now given up, there are just too many issues. Such a shame, I even bought a stack of chromecasts to get whole-house audio, it worked brilliantly when I first installed it.

**Comment by Geo1970** [comment]
Yes, I am having the same problem with Windows 10. Uncheck the device in the menu, the audio disconnects... wait for a few seconds, it re-connects again. I would be really interested to know if this gets fixed. Many thanks Acidhax.

**Comment by matbeedotcom** [comment]
Still an issue with latest release, I'm looking into it.
