### ISSUE TITLE
Popup is weirdly placed

### ISSUE THREAD

**Issue by EricTousignant** [acidhax/chromecast-audio-stream#46]
Hello, it seems the popup that opens when I left-click on the icon prefers the top/left of my screen.
Weirdly, when I right-click, it's in the correct place...
![popup](https://cloud.githubusercontent.com/assets/2239084/17637333/f656251c-60b0-11e6-83f7-ae69631d5c0a.png)

It also displays an empty line that can be selected, then throws a JS error.
![error](https://cloud.githubusercontent.com/assets/2239084/17637353/0f6300de-60b1-11e6-875e-677cc804b319.png)

Thank you for the great work, we all wish for this app to be the best!

**Comment by KZNcode** [comment]
Not sure what exactly fixed it for me, but I did download the 'master' source file and overwritten all the release files with the master--I had to manually copy/paste them to different locations, as the source doesn't exactly match the release file structure.

Also installed BonjourPSSetup.exe from the master.

**Comment by matbeedotcom** [comment]
Please verify this is still an issue by testing https://github.com/acidhax/chromecast-audio-stream/releases/download/0.3/audio-cast-win32-ia32.zip
