### ISSUE TITLE
Chromecasting To TV audio Not Working

### ISSUE THREAD

**Issue by FigureFour13** [acidhax/chromecast-audio-stream#48]
Hello all,
Since late last night I've been searching and searching and nothing is working for me.
So, I'm using Kodi and it works fine on my PC, Windows 7. When I "Cast Desktop" the video does appear on my TV but there's no audio. I'm using a Chromecast and using Chrome to transfer the video.

I've tried: chrome://flags/#try-supported-channel-layouts still not working. 
I've tried: chrome://flags/#disable-audio-support-for-desktop-share still not working. 
I've tried Audio Cast, which it did work for one night then when I tried today to show my GF, it doesn't work properly. I can either cast video with no audio or cast audio with no video when using this program.

I've googled everything I could find for about 5 hours in total between today and last night and nothing is working for me.
Any ideas?
Thanks and I know there's plenty of posts about this, but nothing is working for me.
Thanks and I apologize in advanced.

**Comment by Pealy** [comment]
Hate to say it but you're flogging a dead horse. Until Acidhax can spare some serious time, or someone else with the right skills can pick it up I think we're left with a great idea which just isn't stable.

**Comment by matbeedotcom** [comment]
Yeah, I've got work to do

**Comment by matbeedotcom** [comment]
Please verify this is still an issue by testing https://github.com/acidhax/chromecast-audio-stream/releases/download/0.3/audio-cast-win32-ia32.zip
