### ISSUE TITLE
Connects but no audio - windows 10

### ISSUE THREAD

**Issue by kingkongballs** [acidhax/chromecast-audio-stream#49]
I'm probably doing something wrong, although I did try with the regular chromecast and had nothing, so I bought an audio and still nothing.
Am I meant to change my audio output settings? if so, what to, as what I've tried from the menu so far isn't working. I haven't rebooted yet, which might do the trick, but I'm in the middle of something so I can't.

I know a few windows 10 people had problems but that seemed to be solved. Any ideas?

tenks!

**Comment by Pealy** [comment]
My advice would be to give it up until there's some major investment of time. A real shame but that's the way it is, 

I've moved over to http://tuneblade.com/ - same idea, just use the cheap Airplay receivers instead of Chromecasts..

**Comment by matbeedotcom** [comment]
I have an update coming soon.

**Comment by kingkongballs** [comment]
alrighty, I'll wait

**Comment by bluesodium** [comment]
Any idea when we can expect an update/fix? :-(

**Comment by matbeedotcom** [comment]
Soon :)

**Comment by bluesodium** [comment]
ヽ(´▽`)/

**Comment by RAVINDER73** [comment]
Hopefully very soon!!
I am planning to use CC audio in my car with source of music being surface pro2+ Hootoo tripmate2 and CC audio attached to Helix P DSP digitally to extract songs stored in flac format.
Any other suggestion experts want to give including how to set music output settings as I have 400GB worth of music bin 16 and 24 bit?

**Comment by matbeedotcom** [comment]
Please verify this is still an issue by testing https://github.com/acidhax/chromecast-audio-stream/releases/download/0.3/audio-cast-win32-ia32.zip

**Comment by urteper** [comment]
Still same issue.: "connects but no audio"

**Comment by RAVINDER73** [comment]
^Same here.

**Comment by matbeedotcom** [comment]
Can you try this? https://github.com/acidhax/chromecast-audio-stream/issues/55

**Comment by Andulien** [comment]
Same here, run as admin fix does not fix the issue for me :_(

**Comment by RAVINDER73** [comment]
I too did everything but could not fix it. This time though the cast extension of chrome showed the option of this player. And when I shut down my surface pro2 and then restart it, I have to again restart this program other wise its not visible in task bar. I am not computer expert so it will be helpful if some one guides me how to do it from step1.

**Comment by Andulien** [comment]
Have a look at #56
Try placing the Programms folder onto your Desktop and run from there. Seems to have worked for some now.
