### ISSUE TITLE
Unable to BindToObject

### ISSUE THREAD

**Issue by matbeedotcom** [acidhax/chromecast-audio-stream#5]
[dshow @ 02924400] Unable to BindToObject for virtual-audio-capturer
[dshow @ 02924400] Could not find audio only device with name [virtual-audio-capturer] among source devices of type audio.
[dshow @ 02924400] Searching for audio device within video devices for virtual-audio-capturer
[dshow @ 02924400] Could not find audio only device with name [virtual-audio-capturer] among source devices of type video.
audio=virtual-audio-capturer: Input/output error

**Comment by matbeedotcom** [comment]
This happens when the location of the .DLL changes.

**Comment by luigiplr** [comment]
![](http://cdn.meme.am/instances/500x/59073347.jpg)
