### ISSUE TITLE
Group Audio

### ISSUE THREAD

**Issue by diegotrigo** [acidhax/chromecast-audio-stream#50]
Hi there,
Would great having group audio option. I have 3 ChromeCast Audio grouped, but the app won't read it as group, just as individual speakers.

Nice job otherwise.

Diego

**Comment by xamonline** [comment]
i have the opposite issue.  i don't see my individual chromecasts, rather, all i see is the one group i have set up.

**Comment by Andulien** [comment]
Can this be reopened, or is this not anymore an option? I can as well not see my groups of my audio casts only the individual. However I noticed that you are able to select several of the audio casts.
