### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by trevorboultwood** [acidhax/chromecast-audio-stream#51]
Hi, Really like this idea and I haven't found much like this. I have too had some problems. I found that if the computer is not playing any audio apon opening it will not transmit audio.

If you have a problem try opening media and playing and then open the application.

I am not sure how to suggest items as I have only just created an account on github but I have been using it for years. It would be really cool if you could transmit audio and not have to hear it from two systems.  currently I use the program in order to transmit audio from my computer to another room. however I have it playing on my headphones which isn't great and not really needed.  Potentially using a separate audio device. Not sure if that is feasible.

**Comment by hardonthewind** [comment]
When I have managed to get this connected, I merely muted the speakers on my laptop and the took care of the issue.

**Comment by hardonthewind** [comment]
PS. acidhax has sent out a couple messages stating that the software will be updated soon, so stay tuned.

**Comment by matbeedotcom** [comment]
Please verify this is still an issue by testing https://github.com/acidhax/chromecast-audio-stream/releases/download/0.3/audio-cast-win32-ia32.zip
