### ISSUE TITLE
register_run_as_admin.bat

### ISSUE THREAD

**Issue by lars18th** [acidhax/chromecast-audio-stream#55]
Hi,

It's mandatory to execute "register_run_as_admin.bat" inside the folder \resources\bin\driver\ ?
I don't found anything about it in the documentation. So I suggest to describe how to execute it in Windows. Also, please, add a simple "unregister_run_as_admin.bat"... if you install in a temporal folder, you need to call it for "un-install".

Regards.

**Comment by bluesodium** [comment]
yes. it never worked for me... however...

in the driver directory and open register_run_as_admin.bat

change 

regsvr32 %~dp0/audio_sniffer.dll

to

regsvr32 %~dp0audio_sniffer.dll

run as administrator and ta da. Audio sniffer dll succeeded.

works a treat now.

**Comment by matbeedotcom** [comment]
Interesting... I'll try updating that in the readme

**Comment by lars18th** [comment]
Thank you!
