### ISSUE TITLE
Restrict audio casting to a specific application?

### ISSUE THREAD

**Issue by asarun** [acidhax/chromecast-audio-stream#57]
Hi 

First of all, thanks a ton for this app. Totally awesome! Had some initial teething issues getting it to work, but the "run_as_admin" fix and "muting" the volume solved those. I use MediaMonkey as my mediaplayer and stream my songs from my folders/playlists organized there. Works great!

However, given the app casts all audio from the laptop, if I were to play a youtube video or open a browser and some stupid Video Ad auto plays, then it casts that too interfering with the music. 

Is there some way to cast only audio being played through a specific application? I suppose ideally MediaMonkey should do that, but given that doesn't exist, wondering if there's some workaround to make that happen with this? 

Thanks
Arun

**Comment by limor1** [comment]
Where can you set the input audio device?
Maybe it is possible to use http://vb-audio.pagesperso-orange.fr/Cable/index.htm
in order to direct spotify to a "virtual cable" and then have chromecast-stream read from a "virtual cable" thereby restricting the sound stream to a specific application

**Comment by matbeedotcom** [comment]
@limor1 I'll look into that! Looks good!

https://github.com/acidhax/chromecast-audio-stream/blob/master/src/lib.js#L44

Here's where I set the audio device

**Comment by matbeedotcom** [comment]
Not likely to happen
