### ISSUE TITLE
App frozen in taskbar

### ISSUE THREAD

**Issue by olivernybroe** [acidhax/chromecast-audio-stream#6]
When I launch the app it creates the icon in the taskbar, but nothing happens when I right click the Icon or left click. 

Any log I can post for you to see the issue?

**Comment by matbeedotcom** [comment]
You can run the app from command line and get logs!

**Comment by olivernybroe** [comment]
C:\Users\uruloke\Downloads\audio-cast-1.0.0-win32-ia32>
Example app listening at http://192.168.1.119:29960
Selected Audio Device:
Spawned Ffmpeg with command: ffmpeg -list_devices true -f dshow -i dummy pipe:1
An error occurred: ffmpeg exited with code 1: dummy: Immediate exit requested

VIRTUAL DEVICE FOUND

**Comment by matbeedotcom** [comment]
It looks like it's just not detecting any Chromecasts, interesting..

Looking into it :)

**Comment by olivernybroe** [comment]
Oh sorry, that is actually my bad..
I am not using an chromecast I am using an Nvidia Shield TV, I thought your application worked with all Google Cast enabled devices.

**Comment by matbeedotcom** [comment]
I'll look into this as well! I've never tested on Nvidia shield!

**Comment by olivernybroe** [comment]
Nice, thanks for that! 
Could be nice seing this working on Nvidia Shield TV, does it work on other Google Cast enabled devices then chromecast?

**Comment by DrTzatziki** [comment]
Experiencing a similar issue. I click on the icon and nothing pops up. I am trying to use this with a chromecast audio. Log info below:

Example app listening at http://192.168.1.115:52379
Selected Audio Device:
Spawned Ffmpeg with command: ffmpeg -list_devices true -f dshow -i dummy pipe:1
An error occurred: ffmpeg exited with code 1: dummy: Immediate exit requested

VIRTUAL DEVICE FOUND

**Comment by emanuelstanciu** [comment]
Same here:

C:\Chromecast>
C:\Chromecast
Example app listening at http://192.168.1.106:1689
Selected Audio Device:
Spawned Ffmpeg with command: ffmpeg -list_devices true -f dshow -i dummy pipe:1
An error occurred: ffmpeg exited with code 1: dummy: Immediate exit requested

VIRTUAL DEVICE FOUND

I should probably mention that after I initially downloaded the software and ran it from the Downloads folder it worked. Then I moved it to the C:\Chromecast location and I get same behaviour as others.
I tried restarting, stopping service, etc.. nothing works.

**Comment by emanuelstanciu** [comment]
Just managed to fix this after I searched the reddit forums:

You may have to modify the .bat file to unregister the .dll first. Edit the .bat so it looks like this.
regsvr32 -u %~dp0\audio_sniffer.dll /s

regsvr32  %~dp0\audio_sniffer.dll /s

**Comment by DrTzatziki** [comment]
I edited the "register_run_as_admin.bat" file, since it was the only .bat file packaged with the program. same issue when i execute the application.

Example app listening at http://192.168.1.115:59825
Selected Audio Device:
Spawned Ffmpeg with command: ffmpeg -list_devices true -f dshow -i dummy pipe:1
An error occurred: ffmpeg exited with code 1: dummy: Immediate exit requested

VIRTUAL DEVICE FOUND

**Comment by emanuelstanciu** [comment]
@DrTzatziki 
Mine stopped working again today. It was very fiddly anyway, i had to run the .bat file every single time after a reboot.
Now it refuses to do anything. I tried to experiment with the technology and if you are one for hacking, you can get it to work, but I def think this is a UI issue that needs fixing.
1) start audio-cast.exe from the console and you will get something like this:
C:\Chromecast>audio-cast.exe

C:\Chromecast>
C:\Chromecast
Example app listening at http://192.168.1.106:1883
Selected Audio Device:
Spawned Ffmpeg with command: ffmpeg -list_devices true -f dshow -i dummy pipe:1
An error occurred: ffmpeg exited with code 1: dummy: Immediate exit requested

VIRTUAL DEVICE FOUND

2) Take the URL from the output above: in my case - http://192.168.1.106:1883
3) Open that inside your Google Chrome. This is a live stream source that you need to press Play.
4) Using the official Cast extension, cast the tab containing the source.

You should now have a stable source of sound, you can also mute your speakers as this is a direct stream from your audio card. I know this is a major hack, but it's early days..
If @acidhax requires further logs/data/explanations, please let me know.

**Comment by codlike** [comment]
Get the same as people above, have tried running on Win10 32bit laptop and Win10 64 bit desktop, get greyed out icon and this in the log

C:\audiocast>audio-cast.exe

C:\audiocast>
C:\audiocast
Example app listening at http://192.168.1.10:8073
Selected Audio Device:
Spawned Ffmpeg with command: ffmpeg -list_devices true -f dshow -i dummy pipe:1
An error occurred: ffmpeg exited with code 1: dummy: Immediate exit requested

Tried @ariestar tips (thanks) - modifying the .bat file and didnt have any joy

Tried @ariestar (thanks again) - Take the URL from the output above: in my case - http://192.168.1.106:8073 Open that inside your Google Chrome.....

That did work, the audio is streaming ~~but the volume is quite low.~~ (volume low was me being an idiot with the chromecast app volume sorry)

**Comment by DrTzatziki** [comment]
Tried the URL method @ariestar (thanks), but I think I might be doing something wrong:

VIRTUAL DEVICE FOUND
Device requested: /
Spawned Ffmpeg with command: ffmpeg -f dshow -i audio=virtual-audio-capturer -ac
odec libmp3lame -f mp3 pipe:1
An error occurred: ffmpeg exited with code 1: audio=virtual-audio-capturer: Inpu
t/output error

ffmpeg version N-69406-ga73c411 Copyright (c) 2000-2015 the FFmpeg developers
  built on Jan 29 2015 23:07:55 with gcc 4.9.2 (GCC)
  configuration: --arch=x86 --target-os=mingw32 --cross-prefix=/home/videostream
/Downloads/sandbox/mingw-w64-i686/bin/i686-w64-mingw32- --pkg-config=pkg-config
--enable-gpl --enable-libx264 --enable-avisynth --enable-libxvid --enable-libmp3
lame --enable-version3 --enable-zlib --enable-librtmp --enable-libvorbis --enabl
e-libtheora --enable-libspeex --enable-libopenjpeg --enable-gnutls --enable-libg
sm --enable-libfreetype --enable-libopus --disable-w32threads --enable-frei0r --
enable-filter=frei0r --enable-libvo-aacenc --enable-bzlib --enable-libxavs --ext
ra-cflags=-DPTW32_STATIC_LIB --enable-libopencore-amrnb --enable-libopencore-amr
wb --enable-libvo-amrwbenc --enable-libschroedinger --enable-libvpx --enable-lib
ilbc --prefix=/home/videostream/Downloads/sandbox/mingw-w64-i686/i686-w64-mingw3
2 --enable-static --disable-shared --enable-libsoxr --enable-fontconfig --enable
-libass --enable-libutvideo --enable-libbluray --enable-iconv --enable-libtwolam
e --extra-cflags=-DLIBTWOLAME_STATIC --enable-libzvbi --enable-libcaca --enable-
libmodplug --extra-libs=-lstdc++ --extra-libs=-lpng --enable-libvidstab --enable
-libx265 --enable-decklink --extra-libs=-loleaut32 --extra-cflags= --extra-cflag
s= --enable-nonfree --enable-libfdk-aac --disable-libfaac --disable-decoder=aac
--enable-runtime-cpudetect
  libavutil      54. 18.100 / 54. 18.100
  libavcodec     56. 21.101 / 56. 21.101
  libavformat    56. 19.100 / 56. 19.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5.  9.101 /  5.  9.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[dshow @ 041a3c20] Unable to BindToObject for virtual-audio-capturer
[dshow @ 041a3c20] Could not find audio only device with name [virtual-audio-cap
turer] among source devices of type audio.
[dshow @ 041a3c20] Searching for audio device within video devices for virtual-a
udio-capturer
[dshow @ 041a3c20] Could not find audio only device with name [virtual-audio-cap
turer] among source devices of type video.
audio=virtual-audio-capturer: Input/output error

**Comment by matbeedotcom** [comment]
I'll look into this once I'm back from vacation! Sorry for being quiet!

**Comment by emanuelstanciu** [comment]
@acidhax Hi Mathieu, any news on this bug? You help is greatly appreciated.. Cheers

**Comment by matbeedotcom** [comment]
The good news is, I know how to fix it!

The bad news, I haven't fixed it yet!

**Comment by matbeedotcom** [comment]
There's multiple issues in this thread. For "BindToObject" here is where it'll be solved.
https://github.com/acidhax/chromecast-audio-stream/issues/5

**Comment by emanuelstanciu** [comment]
@acidhax Any update on this issue, Mathieu? Is there more info we need to provide? I think it's something that everyone/most people experience at this point, otherwise it's brilliant.

**Comment by matbeedotcom** [comment]
Yep in a day or two I'll push the update :)

**Comment by tomasvilda** [comment]
Maybe there is some progress?

**Comment by emanuelstanciu** [comment]
Don't want to give you more headaches @acidhax, is there any chance we can get it working soon?

**Comment by matbeedotcom** [comment]
Sorry guys, had an accident, dislocated shoulder and all that fun stuff. I'll be working on it soon :(

**Comment by emanuelstanciu** [comment]
@acidhax ahh, so sad to hear that Mathieu, I hope you are recovering well. Thanks for the update and I look forward to see the progress on this great kit. Thanks and get well soon.

**Comment by MayMih** [comment]
URL method works if you use path without spaces and may be wothout admin rights requirement (not C:/ drive root for example). In my case I placed app on the SD card. But that''s rather uncomfortable.

**Comment by kocane** [comment]
Eagerly awaiting a fix for this as well

**Comment by emanuelstanciu** [comment]
@acidhax How are you recovering, my friend? I hope you are well..

**Comment by timo41** [comment]
Hi there,
I have the same issue and would appreciate it so much if you could fix the problem. Thank you a lot for your work!

**Comment by davebirl** [comment]
As reported by ariestar, that is the same issue I have. This is a damn good little application and I would also be willing to pay for a version that works every time. right now, I reckon it loads correctly 1 in 10 times and the other 9 times, I use the work around described by ariestar. thank you for the app and I look forward to seeing a more polished version soon! thanks, DaveB
