### ISSUE TITLE
Unexplained iCloud communication, virus??

### ISSUE THREAD

**Issue by pentiumii400mhz** [acidhax/chromecast-audio-stream#66]
For some reason the solution is trying to connect to: 94598331.members.btmm.icloud.com?

Virus?

//

**Comment by luigiplr** [comment]
There is **nothing** in the source code that would result in the app attempting to connect to that URL.

Can you provide further information on the methods you used to detect the alleged communication?

**Comment by pentiumii400mhz** [comment]
Hi

It came up a error windows with a lot of references to parts of the code and there I can see this link. I think that I can provide a screen shot from it and upload so you can take a look.

I got worried when I saw this call.

**Comment by pentiumii400mhz** [comment]
![chromecasterror](https://cloud.githubusercontent.com/assets/21958884/20258183/a9198040-aa4e-11e6-85c1-1c92192bb1d8.jpg)

**Comment by matbeedotcom** [comment]
Oh, it must have somehow discovered an iCloud service and crashed
