### ISSUE TITLE
Audio quiet in ChromecastAudio Windows 10

### ISSUE THREAD

**Issue by onitreb** [acidhax/chromecast-audio-stream#9]
I've just used this program for the first time, but it seems that the audio level is much quieter than when I cast from a google app (Google play music app or from chrome web browser). The windows audio mixer has no affect on volume (by design?).

Tested using spotify web player and itunes. 

Thanks.

**Comment by captain-paranoia** [comment]
Similar problem here, on Win 7. Selecting device in the tray gives the familiar CCA 'chime', but no further audio. ffmpeg process is running, and consuming CPU.

Now, whilst this project is neat, what would be a real killer would be a virtual audio device driver, capable of taking file streams supported by CCA, so avoiding the need for compression. I'm thinking in particular of such a driver with MediaMonkey. And it seems you're the guy with the skills needed to do it, judging by your efforts so far... Good work!

**Comment by mathewbgordon** [comment]
Same issue here on Win10, the volume has to be all the way up to be audible at all.

**Comment by mcprat** [comment]
Do you all have the volume for the volume for the CCA, and for that matter your amps, high enough? You're saying the chime is loud but then actual output quiet, right?
